window.PROMPT_BUILDER_CONFIG = {
  baseCurrencies: ["CHF", "EUR", "USD", "GBP"],
  exchanges: [
    "SIX Swiss Exchange",
    "XETRA Deutsche Börse",
    "LSE London Stock Exchange",
  ],
  defaultExchangeByCurrency: {
    CHF: "SIX Swiss Exchange",
    EUR: "XETRA Deutsche Börse",
    USD: "SIX Swiss Exchange",
    GBP: "LSE London Stock Exchange",
  },
  defaultPresetId: "growth",
  presets: [
    {
      id: "conservative",
      label: "Conservative",
      deLabel: "Konservativ",
      riskAppetite: "Low",
      investmentHorizon: ">=3 years",
      equityMin: 25,
      equityMax: 45,
      minEtfs: 6,
      maxEtfs: 10,
      assetClasses: {
        cash: true,
        bonds: true,
        equities: true,
        commodities: true,
        realEstate: false,
        crypto: false,
      },
    },
    {
      id: "balanced",
      label: "Balanced",
      deLabel: "Ausgewogen",
      riskAppetite: "Balanced",
      investmentHorizon: ">=5 years",
      equityMin: 55,
      equityMax: 75,
      assetClasses: {
        cash: true,
        bonds: true,
        equities: true,
        commodities: true,
        realEstate: false,
        crypto: false,
      },
    },
    {
      id: "growth",
      label: "Growth",
      deLabel: "Wachstum",
      riskAppetite: "High",
      investmentHorizon: ">=10 years",
      equityMin: 75,
      equityMax: 95,
      assetClasses: {
        cash: true,
        bonds: true,
        equities: true,
        commodities: true,
        realEstate: false,
        crypto: true,
      },
    },
    {
      id: "aggressive",
      label: "Aggressive",
      deLabel: "Aggressiv",
      riskAppetite: "Very high",
      investmentHorizon: ">=10 years",
      equityMin: 90,
      equityMax: 100,
      assetClasses: {
        cash: true,
        bonds: false,
        equities: true,
        commodities: true,
        realEstate: true,
        crypto: true,
      },
    },
  ],
};
