window.PROMPT_BUILDER_CONFIG = {
  baseCurrencies: ["CHF", "EUR", "USD", "GBP"],
  defaultBaseCurrency: "CHF",
  exchanges: [
    "SIX Swiss Exchange",
    "XETRA Deutsche Börse",
    "NYSE American Stock Exchange",
    "LSE London Stock Exchange",
  ],
  defaultExchangeByCurrency: {
    CHF: "SIX Swiss Exchange",
    EUR: "XETRA Deutsche Börse",
    USD: "NYSE American Stock Exchange",
    GBP: "LSE London Stock Exchange",
  },
  defaultPresetId: "growth",
  presets: [
    {
      id: "conservative",
      icon: "conservative",
      label: "Conservative",
      deLabel: "Konservativ",
      riskAppetite: "Low",
      investmentHorizon: ">=3 years",
      equityMin: 20,
      equityMax: 40,
      minEtfs: 6,
      maxEtfs: 10,
      assetClasses: {
        cash: true,
        bonds: true,
        equities: true,
        commodities: true,
        realEstate: false,
        crypto: false,
      },
    },
    {
      id: "balanced",
      icon: "balanced",
      label: "Balanced",
      deLabel: "Ausgewogen",
      riskAppetite: "Moderate",
      investmentHorizon: ">=5 years",
      equityMin: 40,
      equityMax: 60,
      minEtfs: 6,
      maxEtfs: 10,
      assetClasses: {
        cash: true,
        bonds: true,
        equities: true,
        commodities: true,
        realEstate: false,
        crypto: false,
      },
    },
    {
      id: "growth",
      icon: "growth",
      label: "Growth",
      deLabel: "Wachstum",
      riskAppetite: "High",
      investmentHorizon: ">=10 years",
      equityMin: 60,
      equityMax: 80,
      minEtfs: 7,
      maxEtfs: 11,
      assetClasses: {
        cash: true,
        bonds: true,
        equities: true,
        commodities: true,
        realEstate: false,
        crypto: true,
      },
    },
    {
      id: "aggressive",
      icon: "aggressive",
      label: "Aggressive",
      deLabel: "Aggressiv",
      riskAppetite: "Very high",
      investmentHorizon: ">=10 years",
      equityMin: 80,
      equityMax: 100,
      minEtfs: 7,
      maxEtfs: 11,
      assetClasses: {
        cash: true,
        bonds: false,
        equities: true,
        commodities: true,
        realEstate: true,
        crypto: true,
      },
    },
  ],
};
